/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.41
 * Generated at: 2017-04-01 17:26:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainMenuDisplay_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("    <title>MainMenuDisplay</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./styles/mystyle.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./styles/transaction.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"./styles/footer.css\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    <!--=============================Banner Welcome to Students Bank Of India Stats=============================================-->\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\" style=\"background-color: #69a5e5; border: 1px solid #69a5e5; height: 50px; color:white\">\r\n");
      out.write("                    <h3 style=\"font-family: Tahoma; text-align: center;\">Welcome to Students Bank Of India</h3>\r\n");
      out.write("                </div>  \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    <!--=============================Banner Welcome to Students Bank Of India Ends=============================================-->\r\n");
      out.write("\r\n");
      out.write("    <!--===============================================Main Content Starts=====================================================-->\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-md-12\">\r\n");
      out.write("            <!--================Main Menu Display Navigation Tabs Code Stats here============================-->\r\n");
      out.write("\r\n");
      out.write("                <!--========================Tab List Starts=====================================-->\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"nav nav-tabs\" role=\"tablist\" >\r\n");
      out.write("                        <li class=\"active\"><a href=\"#Welcome\" data-toggle=\"tab\"><h4>Welcome</h4></a></li>\r\n");
      out.write("                        <li><a href=\"#CreateAccount\" role=\"tab\" data-toggle=\"tab\"><h4>Create Account</h4></a></li>\r\n");
      out.write("                        <li><a href=\"#DepositWithdraw\" role=\"tab\" data-toggle=\"tab\"><h4>Deposit/Withdraw</h4></a></li>\r\n");
      out.write("                        <li><a href=\"#Transaction\" data-toggle=\"tab\"><h4>Transaction</h4></a></li>\r\n");
      out.write("                        <li><a href=\"#DisplayBankStmts\" data-toggle=\"tab\"><h4>Bank Statements</h4></a></li>\r\n");
      out.write("                        <li><a href=\"#CreditCardAuth\" data-toggle=\"tab\"><h4>Credit Card</h4></a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                <!--==========================Tab List Ends=========================================-->\r\n");
      out.write("\r\n");
      out.write("                <!--=========================Tab Content Starts======================================-->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"tab-content\">\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    <!--Welcome Page Code Starts Here-->\r\n");
      out.write("                        <div class=\"active tab-pane\" id=\"Welcome\"><div class=\"container-fluid\"><div class=\"row\">\r\n");
      out.write("                         <div class=\"col-md-8\">\r\n");
      out.write("                             <hgroup>\r\n");
      out.write("                                 <h5>STUDENTS BANK OF INDIA ONLINE SERVICES </h5>\r\n");
      out.write("                                 <h6>(At your convenience, any time anywhere)<br/>StarConnect Mobile Banking Services</h6>\r\n");
      out.write("                             </hgroup>\r\n");
      out.write("                             <p>Bank of Indiaâs StarConnect Mobile Banking Service, is a state of the art facility, which allows you to do virtually all your banking activities from your mobile device. With StarConnect Mobile Banking you can access all your banking accounts with the Bank, 24 hours a day, 365 days a year, from anywhere.\r\n");
      out.write("                             </p>\r\n");
      out.write("\r\n");
      out.write("                            <p>A host of features like your banking transaction details, viewing of Account Balance, Mini Statement, Statement, Self Transfers, Third Party Transfer of funds, Utility Bill payments, Ticket booking features among others will definitely make it the most convenient way for you to conduct your banking activities.</p>\r\n");
      out.write("\r\n");
      out.write("                            <p>M/s PayMate to extend Mobile Payments to all Retail Banking customers.</p> \r\n");
      out.write("\r\n");
      out.write("                            <p>BEWARE of Phishing attacks and Vishing attacks</p>\r\n");
      out.write("\r\n");
      out.write("                            <p>We understand that there are fraudulent e-mails (also known as Phishing e-mails) going out to customers of various banks luring them to update sensitive account information like their, User IDs, Passwords, even transaction Passwords, etc., by clicking on an e-mail link or by visiting a website. Similarly, the same information is also asked via telephone call (globally known as Vishing attack), pretending to be genuine officer from Bank Of India.</p>\r\n");
      out.write("\r\n");
      out.write("                            <p>Kindly donât respond to such Phished emails and fraudulent telephone calls .</p>\r\n");
      out.write("\r\n");
      out.write("                            <p>Report Phishing and Vishing <br/>\r\n");
      out.write("                            Contact - </p>\r\n");
      out.write("\r\n");
      out.write("                            <p>Email:- infosecurity@bankofindia.co.in</p>\r\n");
      out.write("\r\n");
      out.write("                            <p>OUR CALL CENTRE NUMBER - 91-22-40919191 (all days) <br/>\r\n");
      out.write("                            06:00 a.m. â 11:00 p.m. (IST)</p>\r\n");
      out.write("                        </div><!--end of tab1-col1-->\r\n");
      out.write("                        <!--div for embeding vedio starts here-->\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                        <div class=\"container-fluid\">\r\n");
      out.write("                            <!-- embed responsive videos -->\r\n");
      out.write("                             <div class=\"embed-responsive embed-responsive-16by9\" style=\"margin-top: 20px\">\r\n");
      out.write("                            <iframe class=\"embed-responsive-item\" src=\"http://www.youtube.com/embed/77vqFwYHi4A\"></iframe>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--div for emdeding vedio ends here-->\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--Welcome Page Code Ends Here-->\r\n");
      out.write("\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("                        \r\n");
      out.write("                        <!--Create Account Page Starts-->\r\n");
      out.write("                        <div class=\"tab-pane\" id=\"CreateAccount\">\r\n");
      out.write("                            <div class=\"container-fluid\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                <!--Create Account Main Starts-->\r\n");
      out.write("                                    <div class=\"col-md-8\">\r\n");
      out.write("                                    <form class=\"form-horizontal\" action=\"create_acc\" method=\"post\">\r\n");
      out.write("                                    <fieldset>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Form Name -->\r\n");
      out.write("                                    <legend>Customer Account Creation Form</legend>\r\n");
      out.write("\r\n");
      out.write("                                    <!--Form elements starts-->\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Text input-->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"Name\">Name </label>  \r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                      <input id=\"CName\" name=\"CName\" type=\"text\" placeholder=\"Enter Name\" class=\"form-control input-md\">\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Text input-->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"DateOfBirth\">DOB</label>  \r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                      <input id=\"CDob\" name=\"CDob\" type=\"text\" placeholder=\"Enter DOB\" class=\"form-control input-md\">  \r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Text input-->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"AddressLine1\">Address Line1</label>  \r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                      <input id=\"CAddrL1\" name=\"CAddrL1\" type=\"text\" placeholder=\"Enter Street no\" class=\"form-control input-md\">\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Text input-->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"AddressLine2\">Address Line2</label>  \r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                      <input id=\"CAddrL2\" name=\"CAddrL2\" type=\"text\" placeholder=\"Enter City, Distict\" class=\"form-control input-md\">\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Select Basic -->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"State\">State</label>\r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                        <select id=\"CState\" name=\"CState\" class=\"form-control\">\r\n");
      out.write("                                          <option value=\"1\">Jammu&Kashmir</option>\r\n");
      out.write("                                          <option value=\"2\">HimachalPradesh</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Text input-->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"email\">Registered EmaiId</label>  \r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                      <input id=\"CEmail\" name=\"CEmail\" type=\"text\" placeholder=\"Enter reg. emailId\" class=\"form-control input-md\">\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <!-- Text input-->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"accountNo\">Account Number</label>  \r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                      <input id=\"accountNo\" name=\"accountNo\" type=\"text\" placeholder=\"Enter Account Number\" class=\"form-control input-md\">\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Select Basic -->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"TypeOfAccount\">TypeOfAccount</label>\r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                        <select id=\"CAccType\" name=\"CAccType\" class=\"form-control\">\r\n");
      out.write("                                          <option value=\"1\">Savings</option>\r\n");
      out.write("                                          <option value=\"2\">Current</option>\r\n");
      out.write("                                          <option value=\"3\">Loans</option>\r\n");
      out.write("                                          <option value=\"4\">Term Deposits</option>\r\n");
      out.write("                                        </select>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                  <!-- Select Multiple -->\r\n");
      out.write("                                  <!--  <div class=\"form-group\">  --> \r\n");
      out.write("                                    <!--  <label class=\"col-md-4 control-label\" for=\"AccountAccess\">Account Access</label> --> \r\n");
      out.write("                                      <!--  <div class=\"col-md-5\"> -->\r\n");
      out.write("                                        <!-- <select id=\"AccountAccess\" name=\"AccountAccess\" class=\"form-control\" multiple=\"multiple\"> -->\r\n");
      out.write("                                          <!--<option value=\"1\">ATM</option>  -->\r\n");
      out.write("                                          \t<!-- <option value=\"2\">Bank</option>-->\r\n");
      out.write("                                          <!-- <option value=\"3\">Phone Banking</option> -->\r\n");
      out.write("                                          <!--<option value=\"4\">Internet Banking</option>  -->\r\n");
      out.write("                                        <!-- </select> -->\r\n");
      out.write("                                      <!--</div>  -->\r\n");
      out.write("                                    <!--</div>  -->\r\n");
      out.write("                                    <br/>\r\n");
      out.write("                                    <!-- Button -->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                    <label class=\"col-md-4 control-label\" for=\"submitbutton\"> </label>\r\n");
      out.write("                                    <div class=\"col-md-4\">\r\n");
      out.write("                                    <button id=\"createAccount\" name=\"createAccount\" class=\"btn btn-primary\">Create Account</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <!--Form elements ends-->\r\n");
      out.write("                                    </fieldset>\r\n");
      out.write("                                    </form>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!--Create Account Page Main Ends-->\r\n");
      out.write("\r\n");
      out.write("                                <!--Create Account Page Side Starts -->\r\n");
      out.write("                                <div class=\"col-md-4\">Side</div>\r\n");
      out.write("                                <!--Create Account Page Side Ends -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--Create Account Section Ends-->\r\n");
      out.write("                        \r\n");
      out.write("\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("                        \r\n");
      out.write("                        <!--Deposit Withdraw Page Starts-->\r\n");
      out.write("                        <div class=\"tab-pane\" id=\"DepositWithdraw\">\r\n");
      out.write("                            <div class=\"container-fluid\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                <!--DepositWithdraw Main Starts-->\r\n");
      out.write("                                    <div class=\"col-md-8\">\r\n");
      out.write("                                    <form class=\"form-horizontal\" method=\"post\" action=\"depositWithdraw\">\r\n");
      out.write("                                    <fieldset>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Form Name -->\r\n");
      out.write("                                    <legend>Deposit/Withdraw</legend>\r\n");
      out.write("\r\n");
      out.write("                                    <!--Form elements starts-->\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Text input-->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"accountNo\">Account Number</label>  \r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                      <input id=\"accountNo\" name=\"accountNo\" type=\"text\" placeholder=\"Enter Account Number\" class=\"form-control input-md\">\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Text input-->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"amount\">Amount</label>  \r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                      <input id=\"amount\" name=\"amount\" type=\"text\" placeholder=\"Enter Amount\" class=\"form-control input-md\">  \r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Text input-->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"date\">Date</label>  \r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                      <input id=\"date\" name=\"date\" type=\"text\" placeholder=\"Enter Date\" class=\"form-control input-md\">\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Text input-->\r\n");
      out.write("                                    <div class=\"form-group\">\r\n");
      out.write("                                      <label class=\"col-md-4 control-label\" for=\"description\">Description</label>  \r\n");
      out.write("                                      <div class=\"col-md-5\">\r\n");
      out.write("                                      <input id=\"description\" name=\"description\" type=\"text\" placeholder=\"Enter City, Distict\" class=\"form-control input-md\">\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    \r\n");
      out.write("                                    <!-- Button -->\r\n");
      out.write("                                     <div class=\"form-group\">\r\n");
      out.write("                                        <label class=\"col-md-4 control-label\" for=\"deposit\"> </label>\r\n");
      out.write("                                           <div class=\"col-md-4\">\r\n");
      out.write("                                              <button id=\"deposit\" name=\"deposit\" class=\"btn btn-primary\">Deposit</button>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                          <label class=\"col-md-4 control-label\" for=\"withdraw\"> </label>\r\n");
      out.write("                                             <div class=\"col-md-4\">\r\n");
      out.write("                                               <button id=\"withdraw\" name=\"withdraw\" class=\"btn btn-primary\">Withdraw</button>\r\n");
      out.write("                                              </div>\r\n");
      out.write("                                       </div>\r\n");
      out.write("                                    \r\n");
      out.write("\r\n");
      out.write("                                    <!--Form elements ends-->\r\n");
      out.write("                                    </fieldset>\r\n");
      out.write("                                    </form>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <!-- Deposit/Withdraw Page Main Ends-->\r\n");
      out.write("\r\n");
      out.write("                                <!--Deposit/Withdraw Page Side Starts -->\r\n");
      out.write("                                <div class=\"col-md-4\">Side</div>\r\n");
      out.write("                                <!--Deposit/Withdraw Page Side Ends -->\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("<!-- Deposit/Withdraw Ends Here -->\r\n");
      out.write("\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("                        \r\n");
      out.write("                        <!--Transaction Page Starts Here -->\r\n");
      out.write("                        <div class=\"tab-pane\" id=\"Transaction\">\r\n");
      out.write("                            <div class=\"container-fluid\">\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                        <!--========================================Transaction Page Main Starts Here=============================-->\r\n");
      out.write("                                    <div class=\"col-md-8\">\r\n");
      out.write("                                    <!--===================Perform Debit or Credit Operation Starts====================-->\r\n");
      out.write("                                        <div class=\"container\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <form class=\"form-horizontal\" action=\"transaction\" method=\"post\">\r\n");
      out.write("                                                <fieldset>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Form Name -->\r\n");
      out.write("                                                <legend>Peform Debit or Credit Operation</legend>\r\n");
      out.write("\r\n");
      out.write("                                                <!--Form elements starts-->\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"accountNoFrom\">Account Number From</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"accountNoFrom\" name=\"accountNoFrom\" type=\"text\" placeholder=\"Enter Account Number From\" class=\"form-control input-md\">\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                \r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"accountNoTo\">Account Number To</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"accountNoTo\" name=\"accountNoTo\" type=\"text\" placeholder=\"Enter Account Number To\" class=\"form-control input-md\">\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"amount\">Amount</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"amount\" name=\"amount\" type=\"text\" placeholder=\"Enter Amount\" class=\"form-control input-md\">  \r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                \r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"date\">Date</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"date\" name=\"date\" type=\"text\" placeholder=\"Enter Date\" class=\"form-control input-md\">  \r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                \r\n");
      out.write("                                                \r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"description\">Description</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"description\" name=\"description\" type=\"text\" placeholder=\"Enter Description\" class=\"form-control input-md\">  \r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Button -->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                <label class=\"col-md-4 control-label\" for=\"debit\"> </label>\r\n");
      out.write("                                                <div class=\"col-md-4\">\r\n");
      out.write("                                                <button id=\"debit\" name=\"debit\" class=\"btn btn-primary\">Debit From</button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <label class=\"col-md-4 control-label\" for=\"credit\"> </label>\r\n");
      out.write("                                                <div class=\"col-md-4\">\r\n");
      out.write("                                                <button id=\"credit\" name=\"credit\" class=\"btn btn-primary\">Credit To</button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                </fieldset>\r\n");
      out.write("                                                </form>\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    <!--===================Perform Debit or Credit Operation Starts====================-->\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                        <!--========================================Transaction Page Main Ends Here================================-->\r\n");
      out.write("\r\n");
      out.write("                                <!--Transaction Page Side Starts Here-->\r\n");
      out.write("                                    <div class=\"col-md-8\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                <!--Transaction Page Side Ends Here-->\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <!--Transacton Page Ends Here -->\r\n");
      out.write("\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--=========================Display Bank Statement Page Starts here==================================================================-->     \r\n");
      out.write("                        <div class=\"tab-pane\" id=\"DisplayBankStmts\">\r\n");
      out.write("                            <div class=\"container-fluid\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                            <!--Dislay Bank Statement Page Main Starts-->\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("                                    <!--===================Display Bank Statement Operation Starts====================-->\r\n");
      out.write("                                       <form class=\"form-horizontal\" action=\"displayStatement.jsp\">\r\n");
      out.write("                                                <fieldset>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Form Name -->\r\n");
      out.write("                                                <legend>Display Statement</legend>\r\n");
      out.write("\r\n");
      out.write("                                                <!--Form elements starts-->\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"accountNo\">Account Number</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"accountNo\" name=\"accountNo\" type=\"text\" placeholder=\"Enter Account Number\" class=\"form-control input-md\">\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div> \r\n");
      out.write("                                                \r\n");
      out.write("                                              \r\n");
      out.write("                                                \r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"dateFrom\">From</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"dateFrom\" name=\"dateFrom\" type=\"text\" placeholder=\"Enter Date From\" class=\"form-control input-md\">\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"dateTo\">To</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"dateTo\" name=\"dateTo\" type=\"text\" placeholder=\"Enter Date To\" class=\"form-control input-md\">\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!--<script type=\"text/javascript\" src=\"./scripts/ajax1.js\"></script>  -->\r\n");
      out.write("                                                <!-- Button -->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                <label class=\"col-md-4 control-label\" for=\"displayStmt\"> </label>\r\n");
      out.write("                                                <div class=\"col-md-4\">\r\n");
      out.write("                                                <button id=\"diplayStmt\" name=\"displayStmt\" class=\"btn btn-primary\">Display Stmt</button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                </fieldset>\r\n");
      out.write("                                        </form>\r\n");
      out.write("                                        <!--=======================Display Statement in Tabular Form Starts=================-->\r\n");
      out.write("                                      \r\n");
      out.write("                                        \r\n");
      out.write("                                        <div class=\"row\">\r\n");
      out.write("                                            <div class=\"span5\" id=\"displaystmt\">\r\n");
      out.write("                                      \r\n");
      out.write("                                            </div> \r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <!--=======================Display Statement in Tabular Form Ends=================-->\r\n");
      out.write("                                               \r\n");
      out.write("                                    <!--=====================Display Bank Statement Operation Ends======================-->\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            <!--Dislay Bank Statement Page Main Ends-->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("    <!--=========================Dispay Bank Statement Page Ends here==================================================================--> \r\n");
      out.write("\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("<!--=====================================================================================================================================-->\r\n");
      out.write("                    \r\n");
      out.write("                    <!--===========Authorize Credit Card Transaction Starts=============== -->\r\n");
      out.write("                        <div class=\"tab-pane\" id=\"CreditCardAuth\">\r\n");
      out.write("                        <div class=\"container-fluid\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                    <!--==============Authroize Credit Card Main Section===============-->\r\n");
      out.write("                                <div class=\"col-md-8\">\r\n");
      out.write("                                    <!--=================Authroization Form Starts==============-->\r\n");
      out.write("                                        <form class=\"form-horizontal\">\r\n");
      out.write("                                                <fieldset>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Form Name -->\r\n");
      out.write("                                                <legend>Authorize Credit card Transaction</legend>\r\n");
      out.write("\r\n");
      out.write("                                                <!--Form elements starts-->\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"name\">Name</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"name\" name=\"name\" type=\"text\" placeholder=\"Enter Name\" class=\"form-control input-md\">\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"cardNumber\">Card Number</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"cardNumber\" name=\"cardNumber\" type=\"text\" placeholder=\"Enter Card Number\" class=\"form-control input-md\">\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>      \r\n");
      out.write("\r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"cvv2/cvc2\">CVV2/CVC2</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"cvv2/cvc2\" name=\"cvv2/cvc2\" type=\"text\" placeholder=\"Enter CVV2/CVC2 \" class=\"form-control input-md\">\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Text input-->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                  <label class=\"col-md-4 control-label\" for=\"amount\">Amount</label>  \r\n");
      out.write("                                                  <div class=\"col-md-5\">\r\n");
      out.write("                                                  <input id=\"amount\" name=\"amount\" type=\"text\" placeholder=\"Enter Max Amount Limit\" class=\"form-control input-md\">\r\n");
      out.write("                                                  </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                                <!-- Button -->\r\n");
      out.write("                                                <div class=\"form-group\">\r\n");
      out.write("                                                <label class=\"col-md-4 control-label\" for=\"authorize\"> </label>\r\n");
      out.write("                                                <div class=\"col-md-4\">\r\n");
      out.write("                                                <button id=\"authorize\" name=\"authorize\" class=\"btn btn-primary\">Authorize</button>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                </fieldset>\r\n");
      out.write("                                        </form>\r\n");
      out.write("\r\n");
      out.write("                                    <!--Authoriztion Form Ends-->\r\n");
      out.write("                                </div>\r\n");
      out.write("                    <!--==============Authroize Credit Card Main Section===============-->\r\n");
      out.write("                    <!--==========Authorize Credit Card Side Section=======================-->\r\n");
      out.write("                                <div class=\"col-md-4\">\r\n");
      out.write("                                    <img src=\"./images/sbi-card-elite.png\" style=\"margin-top: 20px\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                    <!--==============Authroize Credit Card Side Section===============-->\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    <!--===========Authorize Credit Card Transaction Starts=============== -->\r\n");
      out.write("                    </div>\r\n");
      out.write("        <!--=========================Tab Content Ends======================================-->\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> \r\n");
      out.write("    <!--=================================Main Menu Display Navigation Tabs Code Ends here===============================-->   \r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("<!--===============================================Main Content Ends=====================================================-->\r\n");
      out.write("\r\n");
      out.write("<!--========================================================================================================================->\r\n");
      out.write("<!--========================================================================================================================->\r\n");
      out.write("<!--========================================================================================================================->\r\n");
      out.write("\r\n");
      out.write("<!--===========================================Footer Starts================================================================-->\r\n");
      out.write("<!--=========================================================================================================================-->\r\n");
      out.write("  <!--=========================================================================================================================-->\r\n");
      out.write("  <!--=========================================================================================================================-->\r\n");
      out.write("  <!--============================================Footer Starts===============================================-->\r\n");
      out.write("  <!--footer start from here-->\r\n");
      out.write("    <footer>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("      <div class=\"col-md-4 col-sm-6 footerleft \">\r\n");
      out.write("        <div class=\"logofooter\"> Logo</div>\r\n");
      out.write("        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley.</p>\r\n");
      out.write("        <p><i class=\"fa fa-map-pin\"></i> 210, Aggarwal Tower, Rohini sec 9, New Delhi - Â Â Â Â Â Â Â 110085, INDIA</p>\r\n");
      out.write("        <p><i class=\"fa fa-phone\"></i> Phone (India) : +91 9999 878 398</p>\r\n");
      out.write("        <p><i class=\"fa fa-envelope\"></i> E-mail : info@webenlance.com</p>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-2 col-sm-6 paddingtop-bottom\">\r\n");
      out.write("        <h6 class=\"heading7\">GENERAL LINKS</h6>\r\n");
      out.write("        <ul class=\"footer-ul\">\r\n");
      out.write("          <li><a href=\"#\"> Career</a></li>\r\n");
      out.write("          <li><a href=\"#\"> Privacy Policy</a></li>\r\n");
      out.write("          <li><a href=\"#\"> Terms & Conditions</a></li>\r\n");
      out.write("          <li><a href=\"#\"> Client Gateway</a></li>\r\n");
      out.write("          <li><a href=\"#\"> Ranking</a></li>\r\n");
      out.write("          <li><a href=\"#\"> Case Studies</a></li>\r\n");
      out.write("          <li><a href=\"#\"> Frequently Ask Questions</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-3 col-sm-6 paddingtop-bottom\">\r\n");
      out.write("        <h6 class=\"heading7\">LATEST POST</h6>\r\n");
      out.write("        <div class=\"post\">\r\n");
      out.write("          <p>facebook crack the movie advertisment code:what it means for you <span>August 3,2015</span></p>\r\n");
      out.write("          <p>facebook crack the movie advertisment code:what it means for you <span>August 3,2015</span></p>\r\n");
      out.write("          <p>facebook crack the movie advertisment code:what it means for you <span>August 3,2015</span></p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"col-md-3 col-sm-6 paddingtop-bottom\">\r\n");
      out.write("        <div class=\"fb-page\" data-href=\"https://www.facebook.com/facebook\" data-tabs=\"timeline\" data-height=\"300\" data-small-header=\"false\" style=\"margin-bottom:15px;\" data-adapt-container-width=\"true\" data-hide-cover=\"false\" data-show-facepile=\"true\">\r\n");
      out.write("          <div class=\"fb-xfbml-parse-ignore\">\r\n");
      out.write("            <blockquote cite=\"https://www.facebook.com/facebook\"><a href=\"https://www.facebook.com/facebook\">Facebook</a></blockquote>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"copyright\">\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <p>Â© 2016 - All Rights with Webenlance</p>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col-md-6\">\r\n");
      out.write("      <ul class=\"bottom_ul\">\r\n");
      out.write("        <li><a href=\"#\">webenlance.com</a></li>\r\n");
      out.write("        <li><a href=\"#\">About us</a></li>\r\n");
      out.write("        <li><a href=\"#\">Blog</a></li>\r\n");
      out.write("        <li><a href=\"#\">Faq's</a></li>\r\n");
      out.write("        <li><a href=\"#\">Contact us</a></li>\r\n");
      out.write("        <li><a href=\"#\">Site Map</a></li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--===========================================Footer Ends================================================================-->\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
      out.write("    ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
